vm_name = "buster"
box_version = "1.0.0"
box_changelog = "* New major release"
description = "Vanilla Debian Buster base box"
distro_version = "10.4"
#iso_url = "https=//cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-${var.distro_version}.0-amd64-netinst.iso"
iso_checksum = "ab3763d553330e90869487a6843c88f1d4aa199333ff16b653e60e59ac1fc60b"
playbook = "playbook-vps"
sub_playbook = "env.yml"
inventory = "local"
#playbook_file = "./ansible/${var.playbook}/${var.sub_playbook}"
#inventory_directory = "../ansible/${var.playbook}/inventories/${var.inventory}"
